### ISSUE TITLE
Valorant ranks

### ISSUE THREAD

**Issue by szogun1910** [Forge-Media/teamspeak-bot#3]
hey, would you mind adding the option to integrate the rank with valorant

**Comment by Forge-Media** [comment]
I can't commit to adding this ATM as we don't have any Valorant players. Technically it should not be all that difficult as the bot already supports the Riot Games API, so just a matter of copying the `!registerLOL` plugin and making the necessary changes. 

However, the bot at present has a number of problems due to changes to `ts3-nodejs-library` and `node-csgo` which I'm working to resolve first. The most pressing is a major bug with the CSGO integration which causes the bot to crash.

I've requested support on this here: https://gitter.im/joshuaferrara/node-csgo
